More STD variants
UoB-HPC/BabelStream pull request #115
Opened 2021-12-15 21:57 UTC by tom91136

This PR adds the index-oriented STD implementation (`std-indices`), it's been verified to work with NVHPC 21.9 and the usual C++ compilers with TBB.

This PR also refactors the STD and STD20 implementation to `std-data` and `std-ranges` respectively. 

Currently this is still pending validation with oneDPL but it's ready for high-level reviews; don't merge yet.

2021-12-17 14:39 UTC, tomdeakin requested changes
Looks great on the whole @tom91136 ! Just a few minor things to add along with the oneDPL.

I wonder if we also need to add comments for each version explaining data-parallel vs index-parallel? Maybe put this in a comment at the top of the `.cpp` files.

2021-12-17 14:39 UTC, tomdeakin commented on CMakeLists.txt
> +#set(CMAKE_CXX_COMPILER /home/tom/Downloads/nvhpc_2021_219_Linux_x86_64_cuda_multi/install_components/Linux_x86_64/21.9/compilers/bin/nvc++)
Can you just delete these types of comments for the final merge please?

2021-12-17 14:39 UTC, tomdeakin commented on src/std-indices/STDIndicesStream.cpp
> +// Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
Do you need to change this to UoB?

2021-12-17 14:39 UTC, tomdeakin commented on src/std-indices/STDIndicesStream.h
> +class ranged {
Can you add some high level comments explaining what this is? I.e it’s a lightweight counting iterator which will be used by the STL algorithms …..

2021-12-22 12:23 UTC, tom91136 commented
I've reverted the oneDPL commit for now (there's already a branch that uses pointers based on this branch so force pushing is probably gonna break stuff)

2021-12-22 12:28 UTC, tomdeakin commented on src/std-data/STDDataStream.h
> +// Copyright (c) 2020 Tom Deakin
```suggestion
// Copyright (c) 2020 NVIDIA CORPORATION. All rights reserved.
```

2021-12-22 12:28 UTC, tomdeakin commented on src/std-data/STDDataStream.h
> +// University of Bristol HPC
```suggestion
```

2021-12-22 12:29 UTC, tomdeakin commented on src/std-data/STDDataStream.h
> +// University of Bristol HPC
```suggestion
// Copyright (c) 2021 University of Bristol HPC
```

2021-12-22 12:31 UTC, tomdeakin commented on src/std-data/STDDataStream.cpp
> +// Copyright (c) 2020 Tom Deakin
```suggestion
// Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
// Updated in 2021 by University of Bristol
```

2021-12-22 12:58 UTC, merged