Add Futhark implementation
UoB-HPC/BabelStream pull request #146
Opened 2022-11-15 12:23 UTC by athas

I'm at SC22 and noticed that BabelStream is pretty popular, and I really like the idea of polyglot benchmark suites.  So, here's an implementation in [Futhark](https://futhark-lang.org).  I don't know if this is too obscure a language, but it's easy to invoke from C and C++ and so can use the same tooling as all the C++ implementations.

```
$ cmake -Bbuild -H. -DMODEL=futhark -DFUTHARK_BACKEND=opencl
...
$ make -C build
...
$ $ build/futhark-stream
BabelStream
Version: 4.0
Implementation: Futhark (OpencL)
Running kernels 100 times
Precision: double
Array size: 268.4 MB (=0.3 GB)
Total size: 805.3 MB (=0.8 GB)
Function    MBytes/sec  Min (sec)   Max         Average
Copy        1319634.622 0.00041     0.00141     0.00081
Mul         1338486.404 0.00040     0.00176     0.00081
Add         1355367.262 0.00059     0.00193     0.00098
Triad       1364525.941 0.00059     0.00196     0.00102
Dot         1315743.983 0.00041     0.00178     0.00079

2022-11-17 17:39 UTC, Munksgaard commented
Perhaps the CI scripts should be updated as well?

2022-11-17 17:55 UTC, athas commented
The more exotic implementations also aren't tested in CI, so I intentionally didn't add that to keep the invasiveness of this PR low.  But I can do so if desired, no problem.  (Incidentally, someone really ought to make a GA action for Futhark.)

2022-11-21 02:27 UTC, tom91136 commented
> The more exotic implementations also aren't tested in CI, so I intentionally didn't add that to keep the invasiveness of this PR low. But I can do so if desired, no problem. (Incidentally, someone really ought to make a GA action for Futhark.)

We do have CIs setup for the Rust, Julia, and Java variant so it would be good to have it for Futhark too.
Since it's using CMake, it would follow the CI steps like all other C++ implementations, see <https://github.com/UoB-HPC/BabelStream/blob/main/src/ci-test-compile.sh> and <https://github.com/UoB-HPC/BabelStream/blob/main/.github/workflows/main.yaml>.

2022-11-21 08:06 UTC, athas commented
Alright, I'll add a CI step for Futhark.

2022-12-22 17:25 UTC, tom91136 commented
Thanks for the PR and sorry for the late reply, I'm taking a look now (running benchmarks, etc), one thing I've noticed is the lack of a device enumeration API in the Futhark runtime (but apparently you can set devices, or even be presented a dialog in the OpenCL case), this was a bit problematic as I'm testing machines with more than one OpenCL platform. As a workaround, we may have to implement the device enumeration by replicating the logic in the OpenCL and CUDA models.

2022-12-22 17:33 UTC, athas commented
It wouldn't be difficult to add.  I can take a swing at it.

2022-12-22 17:39 UTC, tom91136 commented
@athas Do have to say, the generated C code for multicore CPU is more readable than a good portion C libraries out there!

2022-12-22 17:45 UTC, athas commented
I can just copy the device enumeration code from the `cuda` and `ocl` implementations if you would prefer to have full functionality.

2022-12-22 17:52 UTC, athas commented
I have added device selection now.

2023-01-27 14:40 UTC, tom91136 commented
I've got benchmark results for a few platforms.
For Nvidia A100, it's on-par with the native CUDA/OpenCL implementation:

![BabelStream 4 0 A100 40G (array size=4 3GB)](https://user-images.githubusercontent.com/3199099/215112180-04def84e-4555-4272-b216-e291db38b5bb.png)


Which is excellent.
For the multicore backend, I think the runtime is lacking NUMA awareness.
On a local Ryzen 5900X (1 NUMA domain) machine with dual channel DDR4 3400MT, I'm seeing comparable performance with OpenMP:

```shell
>./build/omp-stream --arraysize 536870912
BabelStream
Version: 4.0
Implementation: OpenMP
Running kernels 100 times
Precision: double
Array size: 4295.0 MB (=4.3 GB)
Total size: 12884.9 MB (=12.9 GB)
Function    MBytes/sec  Min (sec)   Max         Average
Copy        25610.437   0.33541     0.36010     0.34216
Mul         25402.003   0.33816     0.35810     0.34445
Add         29010.697   0.44414     0.47372     0.45097
Triad       28878.115   0.44618     0.47433     0.45268
Dot         44377.658   0.19356     0.21538     0.20067
>./build/futhark-stream --arraysize 536870912
BabelStream
Version: 4.0
Implementation: Futhark (parallel CPU)
Running kernels 100 times
Precision: double
Array size: 4295.0 MB (=4.3 GB)
Total size: 12884.9 MB (=12.9 GB)
Function    MBytes/sec  Min (sec)   Max         Average
Copy        26107.059   0.32903     0.35351     0.33425
Mul         25928.510   0.33129     0.35788     0.33712
Add         29328.709   0.43933     0.46747     0.44469
Triad       28930.892   0.44537     0.47550     0.45077
Dot         44656.475   0.19236     0.20958     0.19728

```

Performance is still good on a dual socket Intel Xeon Gold 6338 (2 NUMA domains) system compared to OpenMP:

![BabelStream 4 0 Xeon Gold 6338 2 (Triad kernel, array size=4 3GB)](https://user-images.githubusercontent.com/3199099/215113018-d5621fc7-54d1-4dcf-969c-569214e13812.png)

But for a dual socket AMD EPYC 7713 (8 NUMA domains), the performance is quite poor:

![BabelStream 4 0 EPYC 7713 (array size=4 3GB)](https://user-images.githubusercontent.com/3199099/215112400-8f1af5b2-251d-4636-9bf9-9d607d1361a3.png)

I didn't do the scaling here due to time constraints.

2023-01-27 14:41 UTC, athas commented
Yes, the multicore backend is completely NUMA-ignorant.  The GPU backends are much more mature.

2023-01-30 13:10 UTC, tom91136 requested changes

2023-01-30 13:10 UTC, tom91136 commented on src/futhark/FutharkStream.cpp
> +#ifndef ALIGNMENT
@athas

2023-01-30 13:10 UTC, tom91136 commented on src/futhark/model.cmake
> +set(FUTHARK_BACKEND "multicore" CACHE STRING "Futhark compiler backend")
@athas

2023-01-30 16:55 UTC, athas commented on src/futhark/model.cmake
> +set(FUTHARK_BACKEND "multicore" CACHE STRING "Futhark compiler backend")
Done.

2023-10-03 09:00 UTC, athas commented
Apparently [it is impossible for me to do so](https://github.com/orgs/community/discussions/5634) for weird GitHub reasons.  I can see about resolving the conflicts myself.

2023-10-03 09:08 UTC, tom91136 commented
Thanks for the merge,  I've approved it now, let's wait for CI.

2023-10-03 09:12 UTC, tom91136 requested changes
Minor changes to get the CI going again

2023-10-03 09:12 UTC, tom91136 commented on .github/workflows/main.yaml
> +
Can't comment beyond the diff, but for the `test-futhark` entry check the following:
 - Set `runs-on` to 22.04, 18.04 is EOL so it won't find a runner and hang indefinitely 
 - Use checkout@v4 to silence warnings

2023-10-03 11:46 UTC, athas commented
CI fails due to an unrelated job running out of disk space.  I wonder why that is not an issue on the `develop` branch.

2023-10-03 12:57 UTC, merged

2023-10-03 12:59 UTC, tom91136 commented
No worries, it's probably because we ran out of cache due to how big the compilers are (we download and untar NVHPC in the setup). Thanks again and sorry about the slow turnaround.